resource_group_name = "org-rg"
vnet_name           = "org-vnet"
subnet_name         = "org-subnet"
nsg_name            = "org-nsg"
vm_name             = "org-vm"
admin_username      = "adminuser"
admin_password      = "P@ssword1234!"
